name: Tests
on:
  pull-request:
  push:
    paths:
      - '**/*.ts'
      - '**/*.js'
      - '**/*.json'

jobs:
  test:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npx lerna bootstrap
      - run: npm ci
      - run: npm test
