on: [pull_request]

name: Pulumi & Typescript Tests

jobs:
  test:
    name: Jest Tests
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Compile Typescript
        run: npm run build
      - name: Run Tests
        uses: ./
  preview:
    name: Preview
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: scripts/build
      - uses: docker://pulumi/actions
        with:
          args: preview
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: pr
          COMMENT_ON_PR: 1
          PULUMI_ROOT: infrastructure